### PR TITLE
Feature/all documentation

### PR DESCRIPTION
**Pull request by nsamedaisy**

### CODE REVIEW

**Review by kngcl — CHANGES_REQUESTED** [review]
Responsiveness is not working. 
Screenshot from 2023-03-18 13-33-42

**Review by kngcl — CHANGES_REQUESTED** [review]
Commits are in present tense.
Screenshot from 2023-03-18 13-46-36

**Review by nganifaith — CHANGES_REQUESTED** [review]
Great job so far @nsamedaisy. we are almost there.

- [ ] Your sidebar doesn't look like the original. Compare the two images below.

**your design**
Screen Shot 2023-04-04 at 14 56 10

**original design**
Screen Shot 2023-04-04 at 14 56 21

**Comment by nganifaith** [comment]
@nsamedaisy Great job. **Project approve** 🥁🥁🥁🥁🥁🥁🥁🥁🥁 you can go ahead and merge your work

**Pull request merged**
